apiVersion: v1
kind: Pod
metadata:
  labels:
      run: jnlp
spec:
  containers:
  - name: kubectl
    image: joshendriks/alpine-k8s
    command:
    - /bin/cat
    tty: true 
  - name: git
    image: gcr.io/cloud-builders/git
    command:
    - cat
    tty: true
#  - name: python-382
#    image: registry.hub.docker.com/library/python:3.8.2
#    command:
#    - cat
#    tty: true
#  - name: busybox
#    image: busybox
#    command:
#    - cat
#    tty: true
#  - name: gcloud
#    image: google/cloud-sdk:latest
#    command:
#    - cat
#    tty: true   
#    volumeMounts:
#      - name: kaniko-secret
#        mountPath: /secret
#    env:
#      - name: GOOGLE_APPLICATION_CREDENTIALS
#        value: /secret/kaniko-secret.json         
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: kaniko-secret
#        mountPath: /secret
        mountPath: /kaniko/.docker
#    env:
#      - name: GOOGLE_APPLICATION_CREDENTIALS
#        value: /secret/kaniko-secret.json
  volumes:
    - name: kaniko-secret
      secret:
#        secretName: kaniko-secret
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
#  imagePullSecrets:
#  - name: jenkins-image-pull-secret