pipeline {
    agent {
        kubernetes {
            defaultContainer 'jnlp'
            yamlFile 'builder.yaml'
        }
    }
    environment {
    }
    stages {
        stage ('Pre Actions-Build Started') {
            steps {
                slackSend (
                  color: '#F7A200' ,
                  message: "Hey, your CI/CD trigger has *Started* \n*Trigger: * `${env.JOB_NAME}` #${env.BUILD_NUMBER}\n<https://jenkins.cams7.ml/job/${env.JOB_NAME}/${env.BUILD_NUMBER}|OPEN JENKINS BUILD>\n*GitHub: * ${GIT_BRANCH} >> <${GIT_URL}|Open Github>" 
                )
            }
        }        
    }
    post {
        success {
            slackSend (
                color: '#00FF00', 
                message: "Hurray! CI/CD is *Success* \n*Trigger: * `${env.JOB_NAME}` #${env.BUILD_NUMBER}\n<https://jenkins.cams7.ml/job/${env.JOB_NAME}/${env.BUILD_NUMBER}|OPEN JENKINS BUILD>\n*GitHub: * ${GIT_BRANCH} >> <${GIT_URL}|Open Github>"
            )
        }
        failure {   
            slackSend (
                color: '#FF0000', 
                message: "Oops, something wrong; CI/CD *Failed* \n*Trigger: * `${env.JOB_NAME}` #${env.BUILD_NUMBER}\n<https://jenkins.cams7.ml/job/${env.JOB_NAME}/${env.BUILD_NUMBER}|OPEN JENKINS BUILD>\n*GitHub: * ${GIT_BRANCH} >> <${GIT_URL}|Open Github>"
            )
        }
    }
}
