pipeline {
    agent {
        kubernetes {
            defaultContainer 'jnlp'
           yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
      run: jnlp
spec:
  containers:
  - name: kubectl
    image: joshendriks/alpine-k8s
    command:
    - /bin/cat
    tty: true 
  - name: git
    image: gcr.io/cloud-builders/git
    command:
    - cat
    tty: true         
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
"""
        }
    }    
    stages {
        stage ('Pre Actions-Build Started') {
            steps {
                slackSend (
                  color: '#F7A200' ,
                  message: "Hey, your CI/CD trigger has *Started* \n*Trigger: * `${env.JOB_NAME}` #${env.BUILD_NUMBER}\n<https://jenkins.cams7.ml/job/${env.JOB_NAME}/${env.BUILD_NUMBER}|OPEN JENKINS BUILD>" 
                )
            }
        }
        stage ('git clone - main') {
            when {
                branch 'main'
            }
            steps{
                container('git'){

                    git branch: 'main',
                        credentialsId: 'CAMs7-Github-Account-Credentials',
                        url: 'https://github.com/cams7/CI-CD-on-Kubernetes.git'
                }
            }
        }        
    }
    post {
        success {
            slackSend (
                color: '#00FF00', 
                message: "Hurray! CI/CD is *Success* \n*Trigger: * `${env.JOB_NAME}` #${env.BUILD_NUMBER}\n<https://jenkins.cams7.ml/job/${env.JOB_NAME}/${env.BUILD_NUMBER}|OPEN JENKINS BUILD>"
            )
        }
        failure {   
            slackSend (
                color: '#FF0000', 
                message: "Oops, something wrong; CI/CD *Failed* \n*Trigger: * `${env.JOB_NAME}` #${env.BUILD_NUMBER}\n<https://jenkins.cams7.ml/job/${env.JOB_NAME}/${env.BUILD_NUMBER}|OPEN JENKINS BUILD>"
            )
        }
    }
}
